
[build]
  command = "npx update-browserslist-db@latest && npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8080

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
