// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzrjqiqlpwcxagclcuei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6cmpxaXFscHdjeGFnY2xjdWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0OTk5NjQsImV4cCI6MjA1ODA3NTk2NH0.oQEFZnmj2waDwEbjA4h922VqYY-PXJFPBz4B-axs54o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);